CREATE TABLE IF NOT EXISTS STEAM_BUNDLE_TEST
(
    ID        VARCHAR(32) NOT NULL
        PRIMARY KEY,
    BUNDLE_ID INT         NOT NULL,
    CONSTRAINT STEAM_BUNDLE_BUNDLE_ID_UINDEX
        UNIQUE (BUNDLE_ID)
);

CREATE TABLE IF NOT EXISTS STEAM_GAME_TEST
(
    ID    VARCHAR(32) NOT NULL
        PRIMARY KEY,
    APPID INT         NOT NULL,
    CONSTRAINT APPID
        UNIQUE (APPID)
);

CREATE TABLE IF NOT EXISTS STEAM_BUNDLE_APP_MAP_TEST
(
    BUNDLE_ID VARCHAR(32) NOT NULL,
    APP_ID    VARCHAR(32) NOT NULL,
    PRIMARY KEY (BUNDLE_ID, APP_ID),
    CONSTRAINT STEAM_BUNDLE_APP_MAP_TEST_STEAM_BUNDLE_TEST_ID_FK
        FOREIGN KEY (BUNDLE_ID) REFERENCES STEAM_BUNDLE_TEST (ID),
    CONSTRAINT STEAM_BUNDLE_APP_MAP_TEST_STEAM_GAME_TEST_ID_FK
        FOREIGN KEY (APP_ID) REFERENCES STEAM_GAME_TEST (ID)
);
